rnsim:
    # ID numbers of the UWB nodes, we are using a convention where the list is
    # supposed to be plit into two rows, first row lists the supposedly static
    # nodes (anchors), and second row is for moving nodes
    nodes_id:
        [100, 101, 102, 103,
         200]
    # 3D position of the nodes in the supposed World coordinates systems, each
    # row should have three coordinates (x, y, z) of the corresponding node on
    # startup. If the node's coordinate is undetermined on startup, put 9999
    # into it.
    nodes_pos:
        [5,  5, 1,
         -5, 5, 0,
         -5, -5, 1,
         5,  -5, 0,
         9999, 9999, 9999
        ]
    # 3D coordinates of the anchors in each node's body frame. Each row starts
    # with the node's ID, then the number of antennas, then the triplets of
    # anchor coordinates. Nodes that don't have anything declared for them are
    # assumed to have a single antenna at its origin
    antennas_pos:
        [200, 2, 0.0, 0.25, 0.0, 0.0, -0.25, 0.0,
         201, 2, 0.0, 0.0, 0.0, 0.0, 0.25, 0.0]
    # Slot map, each row starts with the slot ID, followed by requestor ID,
    # responder ID, requester antenna ID, responder antenna ID, and time period.
    # If two transactions occur at the same time, the time period of the firstly
    # declared transaction is the time period of the slot.
    slotmap:
        [0, 200, 100, 0, 0, 0.025,
         1, 101, 102, 0, 0, 0.050,
         1, 200, 100, 1, 0, 0.025,
         2, 200, 101, 0, 0, 0.025,
         3, 200, 101, 1, 0, 0.025,
         4, 200, 102, 0, 0, 0.025,
         5, 200, 102, 1, 0, 0.025,
         6, 200, 103, 0, 0, 0.025,
         7, 200, 103, 1, 0, 0.025]
    # Name of topics for ground truth, each row specify the ID of the node
    # follow
    ground_truth_topic:
        ["200", "/vicon/firefly_sbx/firefly_sbx"]